language: d
dist: bionic

addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - libc6-dbg
      - glibc-source

before_script:
  - apt show libc6
  - apt list | grep installed
  - ulimit -c unlimited -S       # enable core dumps
  - sudo mkdir /cores/ && sudo chmod 777 /cores/
  - echo "/cores/%E.%p" | sudo tee /proc/sys/kernel/core_pattern

script:
  - ./travis-ci.sh

after_failure:
  - ./core-dump.sh

jobs:
  include:
    - d: dmd-2.089.1
      env: [FRONTEND=2.089]
    - d: ldc-1.18.0
      env: [FRONTEND=2.088]
    - d: ldc-1.19.0
      env: [FRONTEND=2.089]
    - d: dmd-2.088.1
      env: [FRONTEND=2.089]

stages:
  - name: test
    if: type = pull_request or (type = push and branch = master)
  # Until deployment of the release binaries is fixed, always build them
  #- name: deploy
    #if: type = push and tag =~ ^v\d+\.\d+\.\d+[^-]*\$ # not a pre-release tag
  - name: update-latest
    if: type = push and tag =~ ^v\d+\.\d+\.\d+[^-]*\$ # not a pre-release tag
